services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG: '{"id":1,"nodes":[{"id":1,"addr":"service1"},{"id":2,"addr":"service2"},{"id":3,"addr":"service3"}]}'
    ports:
      - "8080:80"
    networks:
      - raft
    expose:
      - "80"
  service2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG: '{"id":2,"nodes":[{"id":1,"addr":"service1"},{"id":2,"addr":"service2"},{"id":3,"addr":"service3"}]}'
    ports:
      - "8081:80"
    networks:
      - raft
    expose:
      - "80"
  service3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG: '{"id":3,"nodes":[{"id":1,"addr":"service1"},{"id":2,"addr":"service2"},{"id":3,"addr":"service3"}]}'
    ports:
      - "8082:80"
    networks:
      - raft
    expose:
      - "80"
networks:
  raft:
    # Specify driver options
    driver: bridge