services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG: '{"id":1,"nodes":[{"id":1,"addr":"0.0.0.0:8080"},{"id":2,"addr":"0.0.0.0:8081"},{"id":3,"addr":"0.0.0.0:8082"}]}'
    ports:
      - "8080:8080"
  server2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG: '{"id":2,"nodes":[{"id":1,"addr":"0.0.0.0:8080"},{"id":2,"addr":"0.0.0.0:8081"},{"id":3,"addr":"0.0.0.0:8082"}]}'
    ports:
      - "8081:8081"
  server3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG: '{"id":3,"nodes":[{"id":1,"addr":"0.0.0.0:8080"},{"id":2,"addr":"0.0.0.0:8081"},{"id":3,"addr":"0.0.0.0:8082"}]}'
    ports:
      - "8082:8082"